POST http://localhost:4000/create-event
Content-Type: application/json

{
    "title":"Tech Fest",
    "date_time":"2025-08-15T08:20:30.123Z",
    "location":"Hyderabad",
    "capacity":600
}

###
POST http://localhost:4000/register-event 
Content-Type: application/json

{
    "user_id":1,
    "event_id":8
}

###
DELETE  http://localhost:4000/cancel-registration
Content-Type: application/json

{
    "user_id":1,
    "event_id":11
}

###
GET http://localhost:4000/upcoming-events

###
GET http://localhost:4000/event-stats/8

###
GET http://localhost:4000/event-details/10